config/routes.rb
Spravkpg::Application.routes.draw do
  resources :rubrics

  resources :companies

  root :to => "home#index"

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_ancestry
  attr_accessible :adress, :email, :name, :rubric, :tel, :parent_id
end

app/models/rubric.rb
class Rubric < ActiveRecord::Base
  has_ancestry
  attr_accessible :parent_id, :slug, :title
end

app/controllers/application_controller.rb
# coding: utf-8
class ApplicationController < ActionController::Base
  protect_from_forgery
	
end

app/controllers/companies_controller.rb
# coding: utf-8
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new
    

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])
    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company refreshed.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
# coding: utf-8
class HomeController < ApplicationController
  def index
  end
end

app/controllers/rubrics_controller.rb
class RubricsController < ApplicationController
  # GET /rubrics
  # GET /rubrics.json
  def index
    @rubrics = Rubric.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rubrics }
    end
  end

  # GET /rubrics/1
  # GET /rubrics/1.json
  def show
    @rubric = Rubric.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rubric }
    end
  end

  # GET /rubrics/new
  # GET /rubrics/new.json
  def new
    @rubric = Rubric.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rubric }
    end
  end

  # GET /rubrics/1/edit
  def edit
    @rubric = Rubric.find(params[:id])
  end

  # POST /rubrics
  # POST /rubrics.json
  def create
    @rubric = Rubric.new(params[:rubric])

    respond_to do |format|
      if @rubric.save
        format.html { redirect_to @rubric, notice: 'Rubric was successfully created.' }
        format.json { render json: @rubric, status: :created, location: @rubric }
      else
        format.html { render action: "new" }
        format.json { render json: @rubric.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rubrics/1
  # PUT /rubrics/1.json
  def update
    @rubric = Rubric.find(params[:id])

    respond_to do |format|
      if @rubric.update_attributes(params[:rubric])
        format.html { redirect_to @rubric, notice: 'Rubric was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rubric.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rubrics/1
  # DELETE /rubrics/1.json
  def destroy
    @rubric = Rubric.find(params[:id])
    @rubric.destroy

    respond_to do |format|
      format.html { redirect_to rubrics_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper

def nested_companies(companies)
  companies.map do |message, sub_companies|
    render(message) + content_tag(:div, nested_companies(sub_companies), :class => "nested_companies")
  end.join.html_safe
end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rubrics_helper.rb
module RubricsHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Имя' %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label 'Email' %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label 'Адрес'%><br />
    <%= f.text_field :adress %>
  </div>
  <div class="field">
    <%= f.label 'Телефон' %><br />
    <%= f.text_field :tel %>
  </div>
  <div class="field">
    <%= f.label 'Рубрика' %><br />
    <%= f.number_field :rubric %>
  </div>
  <div class="field">
    <%= f.label 'ID родителя' %><br />
    <%= f.number_field :parent_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Редактирование компании</h1>

<%= render 'form' %>

<%= link_to 'Показать', @company %> |
<%= link_to 'Назад', companies_path %>

app/views/companies/index.html.erb
<h1>Листинг компаний</h1>

<table>
  <tr>
    <th>Название</th>
    <th>Email</th>
    <th>Адрес</th>
    <th>Тел</th>
    <th>Рубрика</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<p>
 

<% @companies.each do |company| %>
  <tr>
    <td><%= company.name %></td>
    <td><%= company.email %></td>
    <td><%= company.adress %></td>
    <td><%= company.tel %></td>
    <td><%= company.rubric %></td>
    <td><%= link_to 'Показать ', company %></td>
    <td><%= link_to 'Редактировать', edit_company_path(company) %></td>
    <td><%= link_to 'Удалить', company, method: :delete, data: { confirm: 'Точнаа?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Новая комания', new_company_path %>

app/views/companies/new.html.erb
<h1>Новая компания</h1>

<%= render 'form' %>

<%= link_to 'Назад', companies_path %>

app/views/companies/show.haml
%div#breadcrumbs
  - for comp in @company.ancestors
    = link_to h(comp.name), comp
    

%p
  %b Название: 
  = @company.name 


%p
  %b Email:
  =  @company.email 


%p
  %b Адрес: 
  = @company.adress 


%p
  %b Тел:  
  = @company.tel 


%p
  %b Рубрика:  
  = @company.rubric 

= link_to 'Редактировать', edit_company_path(@company)  |
= link_to 'Назад', companies_path 

app/views/companies/show.html.erb
%p{:id=>"notice"} = notice 

%p
  %bНазвание: = company.name 


%p
  %bEmail: = company.email 


%p
  %bАдрес: = @company.adress 


%p
  %bТел:  = @company.tel 


%p
  %bРубрика:  = @company.rubric 


= link_to 'Редактировать', edit_company_path(@company)  |
= link_to 'Назад', companies_path 

app/views/home/index.html.erb
<h1>Добро пожаловать в СпРаВоЧнЕчЕг!</h1>
<%= link_to "Увидеть список компаний", companies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>СпРаВоЧнЕчЕг</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rubrics/_form.html.haml
= form_for @rubric do |f|
  - if @rubric.errors.any?
    #error_explanation
      %h2= "#{pluralize(@rubric.errors.count, "error")} prohibited this rubric from being saved:"
      %ul
        - @rubric.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :parent_id
    = f.number_field :parent_id
  .field
    = f.label :slug
    = f.text_field :slug
  .actions
    = f.submit 'Save'

app/views/rubrics/edit.html.haml
%h1 Editing rubric

= render 'form'

= link_to 'Show', @rubric
\|
= link_to 'Back', rubrics_path

app/views/rubrics/index.html.haml
%h1 Listing rubrics

%table
  %tr
    %th Название
    %th Parent
    %th Slug
    %th
    %th
    %th

  - @rubrics.each do |rubric|
    %table
      %tr
        - rubric.path.each do |r|
          %td= link_to h(r.title), r
          %td= r.depth 
          %td >


    %tr
    
      %td= rubric.title
      %td

      %td= rubric.parent_id
      %td= rubric.slug
      %td= link_to 'Show', rubric
      %td= link_to 'Edit', edit_rubric_path(rubric)
      %td= link_to 'Destroy', rubric, :method => :delete, :data => { :confirm => 'Are you sure?' }
	



%br

= link_to 'New Rubric', new_rubric_path

app/views/rubrics/new.html.haml
%h1 New rubric

= render 'form'

= link_to 'Back', rubrics_path

app/views/rubrics/show.haml
%div#breadcrumbs
  - for comp in @rubric.ancestors
    = link_to h(comp.title), comp
    &gt;
    

%p
  %b Название: 
  = @rubric.title


%p
  %b Slug:
  =  @rubric.slug


= link_to 'Редактировать', edit_rubric_path(@rubric)  |
= link_to 'Назад', rubrics_path 